### PR TITLE
links of repositories with open issues

### PR DESCRIPTION
**Pull request by makkoncept**
screenshot from 2018-10-04 13-36-29
Included the links of those repositories of the user, which have open issues. So we can easily navigate to the repo, and solve some interesting issues.

@jamesgeorge007 , #1

### CODE REVIEW

**Review by jamesgeorge007 — APPROVED** [review]
The idea seems good :+1:
 Can you come up with some innovation to make the UI more visually appealing.

**Comment by makkoncept** [comment]
screenshot from 2018-10-04 22-35-27

@jamesgeorge007  UI improvements

**Comment by jamesgeorge007** [comment]
@makkoncept It would be great if you could make them in the form of cards. What implemented right now makes the UI cluttered.

**Comment by makkoncept** [comment]
@jamesgeorge007 can you please provide me some links for this, because i am not very familiar with designing and css. 
since there is already a lot of custom css present in the project, i thaught it would be good to use it only, as it will make the page more uniform. Now i am having a hard time figuring out  the precedence of the styles

**Comment by jamesgeorge007** [comment]
@makkoncept List those repositories with open issues in the form of individual cards. Provide a link which will take them to the respective repository.

**Comment by jamesgeorge007** [comment]
@makkoncept Resolve the conflicts!

**Pull request merged**
