### PR TITLE
Improved ui, changed some functions.

### LINKED ISSUE #5: Improve UI
AS per now the UI doesn't look promising.It has to be improved adopting suitable design principles.

### PR DESCRIPTION
**Pull request by Ri2parna**
Closes #5 .

### CODE REVIEW

**Comment by Ri2parna** [comment]
@jamesgeorge007 
Check this.

**Review by jamesgeorge007 — CHANGES_REQUESTED** [review]
Awesome work :tada: 
It seems that you forgot to handle the case when an invalid username is provided.

**Comment by Ri2parna** [comment]
Isn't it handled with the code 
``` if response.status_code != 200 ```?

**Comment by Ri2parna** [comment]
I think this change should do it.

**Review by jamesgeorge007 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
